### DISCUSSION TITLE
Does the ARM64 system work well?

### DISCUSSION THREAD

**Discussion by Seo-yul** [nabsul/kcert#30] [Q&A] [answered]
I tried this on my arm64 system, but I got a pod error and it didn't work properly. I checked the other part, but the most suspicious part is the arm architecture. Is it possible to verify?

**Comment by nabsul** [comment, marked as answer]
Thanks for bringing up! It's currently only building AMD64, but supporting ARM is easy.

I'll try to get that done in the next day or two.

**Reply by nabsul** [reply]
https://github.com/nabsul/kcert/issues/31

**Reply by Seo-yul** [reply]
I'm surprised at the quick!
thank you!

**Reply by nabsul** [reply]
@Seo-yul : Have you had a chance to try out the experimental image?

**Comment by nabsul** [comment]
@Seo-yul: Could you try this image and let me know if it works? `nabsul/kcert:pr-32`

**Reply by Seo-yul** [reply]
I will try and answer within 5 days.

**Reply by Seo-yul** [reply]
I try this. but I can't did it 😭 
```
 kubectl -n kcert logs svc/kcert
standard_init_linux.go:228: exec user process caused: exec format error
```
what can I do?

I edited deploy.yml
```
       containers:
       - name: kcert
         image: nabsul/kcert:pr-32                                                 # here
         ports:
         - containerPort: 80
           name: http
         env:
         - name: ACME__DIRURL
           value: https://acme-staging-v02.api.letsencrypt.org/directory            # here
         - name: ACME__TERMSACCEPTED
           value: "true"                                                             # here
         - name: ACME__EMAIL
           value: my-email@gmail.com                                                  # here
```
           
 and try
```
kubectl apply -f ./deploy.yml


namespace/kcert created
serviceaccount/kcert created
clusterrole.rbac.authorization.k8s.io/kcert created
clusterrolebinding.rbac.authorization.k8s.io/kcert created
role.rbac.authorization.k8s.io/kcert created
rolebinding.rbac.authorization.k8s.io/kcert created
deployment.apps/kcert created
service/kcert created
```

I think kubernetes all right.
just
`deployment READY 0/1`
