### ISSUE TITLE
Multiple namespace support

### ISSUE THREAD

**Issue by nabsul** [nabsul/kcert#4]
Figure out how to get certs for ingresses in different namespaces.

**Comment by nabsul** [comment]
I think I found the solution in this article: https://blog.donbowman.ca/2018/09/06/accessing-a-service-in-a-different-namespace-from-a-single-ingress-in-kubernetes/

KCert can create a service as follows:

```yaml
kind: Service
apiVersion: v1
metadata:
  name: kcert
  namespace: some-namespace
spec:
  type: ExternalName
  externalName: kcert.default.svc.cluster.local
  ports:
  - port: 80
```

This will create a service in namespace `some-namespace` that points to the service in `default`
