### ISSUE TITLE
Support for Istio Gateways

### ISSUE THREAD

**Issue by CmdrSharp** [nabsul/kcert#88]
Hi! First - thanks for a cool project!

Are there any plans to support watching Istio Gateway-objects rather than just Kubernetes ingresses?
The current implementation doesn't work well together with Istio unless you strictly use `Ingress`'es, which removes a fair bit of the feature-set that istio provides through its gateway abstraction.

https://istio.io/latest/docs/tasks/traffic-management/ingress/ingress-control/

**Comment by nabsul** [comment]
I think this would be beyond the scope of KCert (the K is for Kubernetes :-D ). However, I've been thinking of using the KCert code as a base to make a more general certificate management service.

To work generally there would need to be an API/contract for the following actions:
- Initiate certificate creation
- Read/Store certificates
- Receive and respond to http challenges

What would these actions look like in the case of Istio?

**Comment by CmdrSharp** [comment]
Istio is perfectly capable of reading normal `Ingress` objects. For cert-manager, you specify the ingress class on the `Issuer` like so:

```yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-cluster
  namespace: istio-system
spec:
  acme:
    email: ops@deanpetrusek.cloud
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-cluster
    solvers:
    - http01:
        ingress:
          class: istio
```

This makes cert-manager create its ingress objects with a specific annotation like so:

```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: istio
spec:
  rules:
  - host: my.example.com
    http: ...
  tls:
  - hosts:
    - my.example.com # This should match a DNS name in the Certificate
    secretName: ingress-cert # This should match the Certificate secretName
```

That's all there is to it, really. The difference on your end would just be the ability to _scan_ for changes to the classic Istio gateway objects. They look like this:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: ingress-cert
    hosts:
    - my.example.com
```
